name: Ansible Terraform Playbook CI

on:
  push:
    branches:
      - main

jobs:
  run-playbook:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to the latest version

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4  # Updated to the latest version
        with:
          python-version: '3.x'

      # Step 3: Install Ansible and ansible-lint
      - name: Install Ansible and ansible-lint
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint

      # Step 4: Lint all YAML files (both in root and subfolders)
      - name: Lint all YAML files
        run: |
          find . -name "*.yml" -print0 | xargs -0 ansible-lint

      # Step 5: Run the main Ansible Playbook
      - name: Run Ansible Playbook
        run: |
          ansible-playbook terraform-playbook.yml
